DestroyOldData:
  cron: "0 3 1 * *"
  class: "DestroyOldDataWorker"
CheckUsersPaymentsExpirations:
  cron: "0 0 * * *"
  class: CheckUsersPaymentsExpirationsWorker
StartAutoPayments:
  cron: "0 1 * * *"
  class: StartAutoPaymentsWorker
CheckPaymentsStatuses:
  cron: "*/30 * * * *"
  class: CheckPaymentsStatusesWorker
