DestroyOldData:
  cron: "0 3 1 * *"
  class: "DestroyOldDataWorker"
LicenseExpirationNotificaton:
  cron: "0 0 * * *"
  class: "LicenseExpirationNotificatonWorker"
StandaloneValidator:
  cron: "0 0 * * *"
  class: "StandaloneValidatorWorker"
